name: Windows MAUI build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Project_Path: CleanCourse\CleanCourse.csproj
      Windows_Tfm: net10.0-windows10.0.19041.0

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Install MAUI workload
      run: dotnet workload install maui-windows

    - name: Restore
      run: dotnet restore $env:Project_Path

    - name: Build Windows app
      run: dotnet build $env:Project_Path --no-restore -f $env:Windows_Tfm -c $env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Upload Windows build
      uses: actions/upload-artifact@v4
      with:
        name: CleanCourse-Windows-${{ matrix.configuration }}
        path: CleanCourse\bin\${{ matrix.configuration }}\${{ env.Windows_Tfm }}
